default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: paleo_works_development

test:
  <<: *default
  database: paleo_works_test

production:
  <<: *default
  database: paleo_works_production
